version: '3.1'

services:

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "alembic upgrade head; uvicorn app.main:app --host 0.0.0.0 --reload --port 8000"
    restart: always
    depends_on:
      - db


  db:
    image: postgres
    container_name: postgres_mashgin
    restart: always
    tty: true
    environment:
      POSTGRES_USER: admin
      POSTGRES_MULTIPLE_DATABASES: mashgin, mashgin_test
      POSTGRES_PASSWORD: secret1
    ports:
      - "5432:5432"
    volumes:
      - ./api/devops/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./front-end
    volumes:
      - './front-end:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    depends_on:
      - backend

volumes:
  pgdata: