"""empty message

Revision ID: 85bd7c34fbf3
Revises: 
Create Date: 2023-07-30 05:25:33.156602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bd7c34fbf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('id', name=op.f('uq_category_id'))
    )
    op.create_table('menu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('categories_id', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu')),
    sa.UniqueConstraint('id', name=op.f('uq_menu_id'))
    )
    op.create_table('order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order')),
    sa.UniqueConstraint('id', name=op.f('uq_order_id'))
    )
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_name'), 'order', ['name'], unique=False)
    op.create_index(op.f('ix_order_updated_at'), 'order', ['updated_at'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('acquirer', sa.String(), nullable=True),
    sa.Column('bank', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('id', name=op.f('uq_payment_id'))
    )
    op.create_index(op.f('ix_payment_created_at'), 'payment', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_updated_at'), 'payment', ['updated_at'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('id', name=op.f('uq_product_id'))
    )
    op.create_index(op.f('ix_product_created_at'), 'product', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_updated_at'), 'product', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_updated_at'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_created_at'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_payment_updated_at'), table_name='payment')
    op.drop_index(op.f('ix_payment_created_at'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_order_updated_at'), table_name='order')
    op.drop_index(op.f('ix_order_name'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_table('order')
    op.drop_table('menu')
    op.drop_table('category')
    # ### end Alembic commands ###
