"""empty message

Revision ID: a600790df447
Revises: 85bd7c34fbf3
Create Date: 2023-07-30 16:58:14.377621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a600790df447'
down_revision = '85bd7c34fbf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_category_id'), 'category', ['id'])
    op.add_column('menu', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('menu', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_menu_created_at'), 'menu', ['created_at'], unique=False)
    op.create_index(op.f('ix_menu_updated_at'), 'menu', ['updated_at'], unique=False)
    op.create_unique_constraint(op.f('uq_menu_id'), 'menu', ['id'])
    op.create_unique_constraint(op.f('uq_order_id'), 'order', ['id'])
    op.create_unique_constraint(op.f('uq_payment_id'), 'payment', ['id'])
    op.create_unique_constraint(op.f('uq_product_id'), 'product', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_product_id'), 'product', type_='unique')
    op.drop_constraint(op.f('uq_payment_id'), 'payment', type_='unique')
    op.drop_constraint(op.f('uq_order_id'), 'order', type_='unique')
    op.drop_constraint(op.f('uq_menu_id'), 'menu', type_='unique')
    op.drop_index(op.f('ix_menu_updated_at'), table_name='menu')
    op.drop_index(op.f('ix_menu_created_at'), table_name='menu')
    op.drop_column('menu', 'updated_at')
    op.drop_column('menu', 'created_at')
    op.drop_constraint(op.f('uq_category_id'), 'category', type_='unique')
    # ### end Alembic commands ###
