"""empty message

Revision ID: 3389898a3e9d
Revises: df0b4c4a7c43
Create Date: 2023-08-03 01:36:53.733749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3389898a3e9d'
down_revision = 'df0b4c4a7c43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###
