"""empty message

Revision ID: df0b4c4a7c43
Revises: a600790df447
Create Date: 2023-07-31 18:42:59.503632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0b4c4a7c43'
down_revision = 'a600790df447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_method_id', sa.String(), nullable=False))
    op.add_column('order', sa.Column('products_id', sa.ARRAY(sa.Integer()), nullable=True))
    op.drop_index('ix_order_name', table_name='order')
    op.drop_column('order', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_order_name', 'order', ['name'], unique=False)
    op.drop_column('order', 'products_id')
    op.drop_column('order', 'payment_method_id')
    # ### end Alembic commands ###
